Script started on 2020-11-22 23:57:32-07:00
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ m4 s[Kassign4.asm > assign4.a[Ks
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ gcc assign4.s
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ ./a.out
Document   | Words              | Most Frequent | Percentage (Occurence / Total Occurence)
------------------------------------------------------------------------------------------
Document 0 | 16   9  10  13 |        Word 0 | 33% (16/48)
Document 1 |  5  14   3  12 |        Word 1 | 41% (14/34)
Document 2 |  9  14   6   4 |        Word 1 | 42% (14/33)
Document 3 |  5   9   1  11 |        Word 3 | 42% (11/26)
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ .a/[K[K[K./a.out 1 1
Document   | Words              | Most Frequent | Percentage (Occurence / Total Occurence)
------------------------------------------------------------------------------------------
Document 0 | 13  10  16  12 |        Word 2 | 31% (16/51)
Document 1 |  9   2   7  14 |        Word 3 | 43% (14/32)
Document 2 | 10   7  12  16 |        Word 3 | 35% (16/45)
Document 3 |  6   4   5  14 |        Word 3 | 48% (14/29)
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ ./a.out 200 200
Document   | Words              | Most Frequent | Percentage (Occurence / Total Occurence)
------------------------------------------------------------------------------------------
Document 0 |  3  14   4   9  12  15  14   8   1   7   3   4   5   7   3   7 |        Word 5 | 12% (15/116)
Document 1 | 12   4   6  16   8   9  12   6   5   6   1   5  10  13   1  12 |        Word 3 | 12% (16/126)
Document 2 | 11   4   4   6   3   1  13   3   7  16   6  11   6   8   2   1 |        Word 9 | 15% (16/102)
Document 3 | 12   7  16   3  16  11   8   4  16   8   8   9   5   8   4  15 |        Word 2 | 10% (16/150)
Document 4 | 12   7   4  14   8   1  16  14  16   6   9   5  13  10   5   8 |        Word 6 | 10% (16/148)
Document 5 | 16   4  11  15  15   2   2  14  10   9   7  14   1  10  12  12 |        Word 0 | 10% (16/154)
Document 6 |  1  15   9   8  15   8   5  14  13  13   2  10   6   6   1   6 |        Word 1 | 11% (15/132)
Document 7 | 10  11   4   8  13   6   5   6  14  11   3  14   5  14   9   5 |        Word 8 | 10% (14/138)
Document 8 | 12   1  12  11   9  16   8   5  13  10  14   2  15  15   7   8 |        Word 5 | 10% (16/158)
Document 9 |  9  11  15   5  16   4  10  13  14  12  11   2   9   3   6   5 |        Word 4 | 11% (16/145)
Document 10 |  4   1  15  12   1   6  16  13  15  14  14  14  12   5   5   4 |        Word 6 | 10% (16/151)
Document 11 | 15   4   9  14   7   2  10   4  14   4   6   6   7  11  10  10 |        Word 0 | 11% (15/133)
Document 12 | 12   8   5  12  14   4   8  12   1   5   9  12   9  14  16   7 |        Word 14 | 10% (16/148)
Document 13 |  1   8   4   7   9  14  10   6   1  15  12   7  10   5  16   5 |        Word 14 | 12% (16/130)
Document 14 | 13   4  16  10   8   7   5   8  11  14   4   4  11   3  10  11 |        Word 2 | 11% (16/139)
Document 15 | 10  14   1   2  11  10   8  11   9   3   2   2   7   1   6   3 |        Word 1 | 14% (14/100)
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ ./a.out 5 5
Document   | Words              | Most Frequent | Percentage (Occurence / Total Occurence)
------------------------------------------------------------------------------------------
Document 0 |  7  13  16   4   8 |        Word 2 | 33% (16/48)
Document 1 |  9  16   6  14   1 |        Word 1 | 34% (16/46)
Document 2 |  8  10   6   3   6 |        Word 1 | 30% (10/33)
Document 3 | 11  10  13  15   8 |        Word 3 | 26% (15/57)
Document 4 |  8   5  16   4  12 |        Word 2 | 35% (16/45)
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ gdb a[Ka.out
GNU gdb (GDB) Fedora 8.1.1-4.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...(no debugging symbols found)...done.
(gdb) b generate_table_row
Breakpoint 1 at 0x4008c8
(gdb) b print_table
Breakpoint 2 at 0x400a60
(gdb) r
Starting program: /home/ugb/yunfan.yang1/Desktop/cpsc-355/Assignment 4/a.out 
warning: the debug information found in "/usr/lib/debug//usr/lib64/ld-2.27.so.debug" does not match "/lib/ld-linux-aarch64.so.1" (CRC mismatch).

Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-38.fc28.aarch64
warning: the debug information found in "/usr/lib/debug//lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.27.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).


Breakpoint 1, 0x00000000004008c8 in generate_table_row ()
(gdb) c
Continuing.

Breakpoint 1, 0x00000000004008c8 in generate_table_row ()
(gdb) x/4d $x29+$x21
0xfffffffff120:	14	2	15	16
(gdb) c
Continuing.

Breakpoint 1, 0x00000000004008c8 in generate_table_row ()
(gdb) x/8d $x29+$x21
0xfffffffff120:	14	2	15	16
0xfffffffff130:	11	10	13	4
(gdb) c
Continuing.

Breakpoint 1, 0x00000000004008c8 in generate_table_row ()
(gdb) x/12d $x29+$x21
0xfffffffff120:	14	2	15	16
0xfffffffff130:	11	10	13	4
0xfffffffff140:	15	5	14	11
(gdb) c
Continuing.

Breakpoint 1, 0x00000000004008c8 in generate_table_row ()
(gdb) x/2d $x2/0[K[K9+$x22+$x21
0xfffffffff080:	16	0
(gdb) x/2d $x29+$x22+$x21[1P[1@4
0xfffffffff080:	16	0	34	0
(gdb) x/4d $x29+$x22+$x21[C[1P[1@8
0xfffffffff080:	16	0	34	0
0xfffffffff090:	3	0	2025776110	0
(gdb) x/8d $x29+$x22+$x21[C[C[C[C[C[C[Kx/8d $x29+$x22+$x21[C[C[C[C[C[C[Kc
Continuing.

Breakpoint 2, 0x0000000000400a60 in print_table ()
(gdb) cx/8d $x29+$x22+$x21
0xfffffffff080:	16	0	34	0
0xfffffffff090:	3	0	2025776110	0
(gdb) c
Continuing.
Document   | Words              | Most Frequent | Percentage (Occurence / Total Occurence)
------------------------------------------------------------------------------------------
Document 0 | 14   2  15  16 |        Word 3 | 34% (16/47)
Document 1 | 11  10  13   4 |        Word 2 | 34% (13/38)
Document 2 | 15   5  14  11 |        Word 0 | 33% (15/45)
Document 3 |  2  15   4   7 |        Word 1 | 53% (15/28)
[Inferior 1 (process 8558) exited with code 01]
(gdb) q
]0;yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4yunfan.yang1@csa2:~/Desktop/cpsc-355/Assignment 4$ exit
exit

Script done on 2020-11-22 23:59:33-07:00
